<a href="https://colab.research.google.com/github/Bharatgaur/RawProjects/blob/main/Python_Numpy_Full_Tutorial_For_Beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorials

https://youtu.be/-TYSM0CDA4c?si=jlIhoOBrnxMSLLN2

In [ ]:
# ARRAY

import numpy as np
x = [1,2,3,4,5]
y = np.array(x)
print(y)
print(type(y))
y

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [ ]:
l = []

for i in range(1,5):
  int_1 = int(input("enter: "))
  l.append(int_1)

print(np.array(l))

enter: 12
enter: 13
enter: 14
enter: 15
[12 13 14 15]


Dimension in Arrays

1-D Array   [ ]

2-D Array [[ ]]

3-D Array  [[[  ]]]

Higher Dimensional Arrays

In [ ]:
import numpy as np
x = [1,2,3,4,5]
y = np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
ar2 = np.array([[1,2,3,4],[1,2,3]])
print(ar2)
print(ar2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
ar3 =np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Create Numpy Array Using Numpy Functions

In [ ]:
# zeros arrays

import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [ ]:
# zeros arrays

import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Ones

ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [ ]:
# Empty array
# previous array ka data empty array main chala jata hai
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [ ]:
# range
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [ ]:
# Diagonal

ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
ar_dia = np.eye(5,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# linspace
ar_lin = np.linspace(1,10, num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
ar_lin = np.linspace(0,10, num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
ar_lin = np.linspace(0,20, num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [ ]:
ar_lin = np.linspace(0,20, num=4)
print(ar_lin)

[ 0.          6.66666667 13.33333333 20.        ]


In [ ]:
ar_lin = np.linspace(0,30, num=5)
print(ar_lin)

[ 0.   7.5 15.  22.5 30. ]


Creating Numpy Arrays with Random Numbers

- `rand()`: Generates random numbers from a uniform distribution between 0 and 1.

- `randn()`: Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

- `ranf()`: An alias for `rand()`, also generates random numbers from a uniform distribution between 0 and 1.

- `randint()`: Generates random integers from a specified range, including both endpoints.

In [ ]:
# Random
# rand()

import numpy as np

var = np.random.rand(4)
print(var)

[0.11621977 0.39879611 0.66416386 0.6145468 ]


In [ ]:
var1 = np.random.rand(2,5)
print(var1)

[[0.38970435 0.98695753 0.7309118  0.53591511 0.13804834]
 [0.54921271 0.08553459 0.23735297 0.72013976 0.07832975]]


In [ ]:
# randn()

var2 = np.random.randn(5)
print(var2)

[-0.52779674  1.29337706 -0.00357057  0.11478954 -0.25509713]


In [ ]:
# randf()
var3 = np.random.ranf(4)
print(var3)

[0.15731642 0.37423533 0.29263192 0.95333218]


In [ ]:
# randint min value, maximum value
# var4 = np.random.randint(min,max, total_values)
var4 = np.random.randint(5,20,5)
print(var4)


[ 5 19 12 12 14]


Data Types in Numpy Array

In [ ]:
import numpy as np
var = np.array([1,2,3,4])
print('Data type: ', var.dtype)

Data type:  int64


In [ ]:
var = np.array([1.0,2.3,3.6,3.7,4])
print('Data type: ', var.dtype)

Data type:  float64


In [ ]:
var = np.array(['a','s','d','f'])
print('Data type: ', var.dtype)

Data type:  <U1


In [ ]:
var = np.array(['a','s','d','f',1,2,3,4])
print('Data type: ', var.dtype)

Data type:  <U21


In [ ]:
x = np.array([1,2,3,4])

print('Data Type', x.dtype)

Data Type int64


In [ ]:
x = np.array([1,2,3,4],dtype=np.int8)

print('Data Type', x.dtype)
print(x)

Data Type int8
[1 2 3 4]


In [ ]:
x1 = np.array([1,2,3,4],dtype="f")

print('Data Type', x1.dtype)
print(x1)

Data Type float32
[1. 2. 3. 4.]


In [ ]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)

print('Data Type', x2.dtype)

print(x2)
print('Data Type', new.dtype)
print(new)

Data Type int64
[1 2 3 4]
Data Type float32
[1. 2. 3. 4.]


In [ ]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)
print('Data Type', x2.dtype)
print('Data Type', new.dtype)
print('Data Type', new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type int64
Data Type float32
Data Type int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


Shape & Reshaping in Nupy Arrays

In [1]:
import numpy as np
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [2]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [4]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)

print()
print(var.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

2

(1, 1, 1, 4)


In [8]:
# Reshape

var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [9]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1



ValueError: cannot reshape array of size 6 into shape (3,3)

In [12]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x = var3.reshape(2,3,2)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [14]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)
print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [17]:
# Arithmetic operations in numpy array
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [18]:
import numpy as np
var = np.array([1,2,3,4])
var2 = np.array
varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [19]:
var = np.array([1,2,3,4])
var2 = np.array
varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [20]:
var = np.array([1,2,3,4])
var2 = np.array
varadd = var % 3
print(varadd)

[1 2 0 1]


In [25]:
var = np.array([1,2,3,4])
var2 = np.array
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


In [23]:
# 2d array
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
varadd2 = var21 + var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [24]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
varadd2 = var21 * var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [26]:
import numpy as np
var = np.array([1,2,3,4,5,3,2])
print(np.min(var))

1


In [34]:
print("min: " , np.min(var),np.argmin(var))
print("max: " , np.max(var),np.argmax(var))

min:  1 0
max:  5 4


In [38]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1, axis=0))
print()
print(np.min(var1, axis=1))

# row = 1
# column =0

[2 1 3]

[1 5]


In [39]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1, axis=0))
print()
print(np.min(var1, axis=1))
print()
print("sqrt: ", np.sqrt(var))
# row = 1
# column =0

[2 1 3]

[1 5]

sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [27]:
var = np.array([1,2,3,4,5,3,2])


print(np.max(var))

5


In [28]:
var = np.array([1,2,3,4,5,3,2])
print(np.argmin(var))

0


In [29]:
var = np.array([1,2,3,4,5,3,2])
print(np.sin(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427  0.14112001
  0.90929743]


In [30]:
var = np.array([1,2,3,4,5,3,2])
print(np.cos(var))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219 -0.9899925
 -0.41614684]


In [31]:
var = np.array([1,2,3,4,5,3,2])
print(np.cumsum(var))

[ 1  3  6 10 15 18 20]
