<a href="https://colab.research.google.com/github/Bharatgaur/RawProjects/blob/main/Python_Numpy_Full_Tutorial_For_Beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorials

https://youtu.be/-TYSM0CDA4c?si=jlIhoOBrnxMSLLN2

In [4]:
# ARRAY

import numpy as np
x = [1,2,3,4,5]
y = np.array(x)
print(y)
print(type(y))
y

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [6]:
l = []

for i in range(1,5):
  int_1 = int(input("enter: "))
  l.append(int_1)

print(np.array(l))

enter: 12
enter: 13
enter: 14
enter: 15
[12 13 14 15]


Dimension in Arrays

1-D Array   [ ]

2-D Array [[ ]]

3-D Array  [[[  ]]]

Higher Dimensional Arrays

In [7]:
import numpy as np
x = [1,2,3,4,5]
y = np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [8]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [9]:
ar2 = np.array([[1,2,3,4],[1,2,3]])
print(ar2)
print(ar2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
ar3 =np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [11]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Create Numpy Array Using Numpy Functions

In [13]:
# zeros arrays

import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [14]:
# zeros arrays

import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# Ones

ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [17]:
# Empty array
# previous array ka data empty array main chala jata hai
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [18]:
# range
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [19]:
# Diagonal

ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [21]:
ar_dia = np.eye(5,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# linspace
ar_lin = np.linspace(1,10, num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [23]:
ar_lin = np.linspace(0,10, num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
ar_lin = np.linspace(0,20, num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [25]:
ar_lin = np.linspace(0,20, num=4)
print(ar_lin)

[ 0.          6.66666667 13.33333333 20.        ]


In [27]:
ar_lin = np.linspace(0,30, num=5)
print(ar_lin)

[ 0.   7.5 15.  22.5 30. ]


Creating Numpy Arrays with Random Numbers

- `rand()`: Generates random numbers from a uniform distribution between 0 and 1.

- `randn()`: Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

- `ranf()`: An alias for `rand()`, also generates random numbers from a uniform distribution between 0 and 1.

- `randint()`: Generates random integers from a specified range, including both endpoints.

In [28]:
# Random
# rand()

import numpy as np

var = np.random.rand(4)
print(var)

[0.11621977 0.39879611 0.66416386 0.6145468 ]


In [29]:
var1 = np.random.rand(2,5)
print(var1)

[[0.38970435 0.98695753 0.7309118  0.53591511 0.13804834]
 [0.54921271 0.08553459 0.23735297 0.72013976 0.07832975]]


In [31]:
# randn()

var2 = np.random.randn(5)
print(var2)

[-0.52779674  1.29337706 -0.00357057  0.11478954 -0.25509713]


In [32]:
# randf()
var3 = np.random.ranf(4)
print(var3)

[0.15731642 0.37423533 0.29263192 0.95333218]


In [34]:
# randint min value, maximum value
# var4 = np.random.randint(min,max, total_values)
var4 = np.random.randint(5,20,5)
print(var4)


[ 5 19 12 12 14]


Data Types in Numpy Array